inertial_frame_id: world
waypoints:
  -
    point: [-300, -220, -95]
    max_forward_speed: 1
    heading: 0
    use_fixed_heading: False
  -
    point: [-300, -155, -95]
    max_forward_speed: 1
    heading: 0
    use_fixed_heading: False
  -
    point: [-310, -140, -95]
    max_forward_speed: 1
    heading: 0
    use_fixed_heading: False